[package]
name = "comicshelf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6.20"
md5 = "0.7.0"
reqwest = { version = "0.11.18", features = ["json"] }
serde_json = "1.0.104"
tera = "1.19.0"
tokio = { version = "1.30.0", features = ["macros", "rt-multi-thread"] }
tower-http = { version = "0.4.3", features = ["fs"] }
