spring:
  application:
    name: comicshelf
  mvc:
    static-path: /static/**
  web:
    resources:
      static-locations: classpath:/static

logging:
  level:
    com.github.jakedegiovanni.comicshelf: DEBUG
