spring:
  application:
    name: comicshelf
  mvc:
    static-path-pattern: /static/**

logging:
  level:
    root: INFO
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    io.github.jakedegiovanni.comicshelf: DEBUG

marvel:
  base-url: https://gateway.marvel.com/v1/public
  pub: pub.txt # todo - should be able to use more than just filepaths
  priv: priv.txt
