spring:
  application:
    name: comicshelf
  mvc:
    static-path-pattern: /static/**

logging:
  level:
    root: INFO
    io.github.jakedegiovanni.comicshelf: DEBUG

marvel:
  url: https://gateway.marvel.com/v1/public
